/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyApp;

import java.util.Scanner;

public class App {

    public static void gcd() {
        new gcd1();
    } //option1.2
    public static void soe(){
       new soe1();
    } //option2
    public static void match() {
        new match1();
    } //option3
}
